### ISSUE TITLE
Slide button on hero stops animation if clicked while sliding.

### ISSUE THREAD

**Issue by JeppeF** [FameThemes/screenr#121]
Something is wrong with the selective slide buttons on hero.

If i double click fast on button it stops mid-animation. 
Like this:
![screenr-hero-slide-bug](https://cloud.githubusercontent.com/assets/24207284/20648809/248ffd8c-b4b1-11e6-9766-1b2fad37a0b7.png)

If i spam click button after this, it randomly starts again and finishes animation.

It seems to depend on where on the button you click, when trying to start animation again.

EDIT:
I turns out to be the swipe function that can restart the animation, and not clicking the button after it stops.

**Comment by JeppeF** [comment]
While trying to find the cause for this behavior, the issue disappeared. 

I can't reproduce the issue anymore so unless somebody can, it should be closed.

**Comment by KienTrong** [comment]
If the error happen again, feel free to open this issue :)
