### ISSUE TITLE
remove ""This is where you can add new products to your store." on shop page.

### ISSUE THREAD

**Issue by congthien** [FameThemes/screenr#158]

**Comment by shrimp2t** [comment]
Please, Where can find it ?

**Comment by congthien** [comment]
> Please, Where can find it ?

From client report: 

> There was a default subtitle in the header on the shop page, saying "This is where you can add new products to your store." I believe this is a default from WooCommerce that cannot be removed anywhere in the GUI so I added .swiper-slide-desc { display: none; } to hide it. Maybe that should be shipped with the theme?

**Comment by wickywills** [comment]
Just in case others come across this, and since there are no other solutions other than to hide the text with CSS (which doesn't solve the problem!), add this to your functions.php to remove it:

```
add_filter('woocommerce_register_post_type_product',` 'remove_shop_default_description');
function remove_shop_default_description($args){
	$args['description'] = '';
	return $args;
}
```

**Comment by hamishau** [comment]
> Just in case others come across this, and since there are no other solutions other than to hide the text with CSS (which doesn't solve the problem!), add this to your functions.php to remove it:
> 
> ```
> add_filter('woocommerce_register_post_type_product',` 'remove_shop_default_description');
> function remove_shop_default_description($args){
> 	$args['description'] = '';
> 	return $args;
> }
> ```

I know this is old but it still shows as being relevant for related search terms... please correct me if I am wrong, but shouldn't the backtick be removed from the first line for this to work correctly?

```
add_filter('woocommerce_register_post_type_product', 'remove_shop_default_description');
function remove_shop_default_description($args){
$args['description'] = '';
 	return $args;
}
```

Thanks for the information though, this helped me out with a quick fix. All the best.
