### ISSUE TITLE
Add site footer to Theme Options

### ISSUE THREAD

**Issue by Longkt** [FameThemes/screenr#163]
Currently, the section site footer cannot change in the Theme Options. If the client wants to change the text, they have to modify it by use code with the child theme or directly change in the file in https://github.com/FameThemes/screenr/blob/master/inc/extras.php#L898-L914

![3](https://user-images.githubusercontent.com/25312148/50415103-d9bb2200-084b-11e9-9303-2180ca54cef3.PNG)

Should we add this section to the Theme Options?

**Comment by shrimp2t** [comment]
Hey,

This feature existing pro version.

**Comment by Longkt** [comment]
Hi @shrimp2t , thanks for the guide but how can I change the text theme author `Screenr parallax theme by FameThemes`?
