### ISSUE TITLE
Content Width Issue

### ISSUE THREAD

**Issue by sakinshrestha** [FameThemes/screenr#64]
- You have defined content width as 640 in function `screenr_content_width()`. But when I check in your site. Your content width depends on the screensize, where you have css defined as 74.7748%. So, it doesn't match this. If your content with is 640 then you need to set max-width for your `.content-area` in your style.

**Comment by KienTrong** [comment]
@sakinshrestha I have update content width to 790 and set max with for `.entry-content` class.
