### ISSUE TITLE
Double featured image

### ISSUE THREAD

**Issue by justintadlock** [FameThemes/screenr#75]
This is just a note to be mindful that users who use their featured image within the post content will see a featured image on single posts.  This can cause them to see the same image twice.

When displaying the featured image on single posts next to the post content (as in your theme right above the content), it's often a good idea to have an option to allow the user to disable this.

**Comment by KienTrong** [comment]
@shrimp2t Had thinking about it some time ago, so we can do this:

Customizer : Theme Option -> Blog settings
1. Move `Blog title` from page header to it.
2. Post listing meta data (https://cl.ly/2G2S160Z1X2x), can use checkbox for these: Author, Data, Category, Comment -> Display by default.
3. Disable featured image in single post: Checkbox
